### ISSUE TITLE
Error while listing shares

### ISSUE THREAD

**Issue by hegusung** [CoreSecurity/impacket#116]
Hello, I am trying to list shares with an anonymous client and I get the following error :
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/logger.py", line 40, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 324, in getMessage
    msg = str(self.msg)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 764, in __str__
    return 'SMB SessionError: %s(%s)' % (nt_errors.ERROR_MESSAGES[self.error])
KeyError: 4294901762

Do you know how to correct this ?

**Comment by asolino** [comment]
Hey there.. thanks for this bug report.

In order to reproduce this issue I would need a packet capture for that session. Also, did you use a sample script (e.g. smbclient.py) or are developing your our app?

**Comment by asolino** [comment]
Hey @hegusung, do you have any news on this one?

thanks!

**Comment by hegusung** [comment]
I tried with the sample script smbclient.py, unfortunately I don't have access anymore to the server which had the issues, I haven't been able to reproduce this error since
