### ISSUE TITLE
another exception, this time in setup andx processing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CoreSecurity/impacket#18]
```
here's a repro payload:

00000049ff534d42730000000000000000000000000000000000000000005c02000000000dff0000
00ffff02005c02000000000000000000000000010000000b0000004d5300434c49454e5400

and here's a stack trace:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbserver.py", line 2332, in handle
    resp = self.__SMB.processRequest(self.__connId, p.get_trailer())
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbserver.py", line 2651, in processRequest
    packet)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbserver.py", line 2177, in smbComSessionSetupAndX
    sessionSetupData.fromString(SMBCommand['Data'])
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 142, in fromString
    size = self.calcUnpackSize(field[1], data, field[0])
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 464, in calcUnpackSize
    return self.calcUnpackSize(two[0], data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 496, in calcUnpackSize
    return data.index('\x00')+1
ValueError: substring not found
```

Original issue reported on code.google.com by `bryanbu...@gmail.com` on 13 Sep 2012 at 10:08

**Comment by asolino** [comment]
Can't reproduce it anymore
