### ISSUE TITLE
python3 No module named 'ImpactPacket'

### ISSUE THREAD

**Issue by Kcrong** [CoreSecurity/impacket#217]
python code:

```python
from impacket.ImpactDecoder import *
```

error:
```
Traceback (most recent call last):
  File "fakepath/pycharm/helpers/pydev/pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "fakepath/pycharm/helpers/pydev/pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "fakepath/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "fakepath/main.py", line 3, in <module>
    from impacket.ImpactDecoder import *
  File "fakepath/env/lib/python3.4/site-packages/impacket/ImpactDecoder.py", line 16, in <module>
    import ImpactPacket
ImportError: No module named 'ImpactPacket'
```

**Comment by asolino** [comment]
Impacket does not support Python3 at the moment. This is a duplicate for https://github.com/CoreSecurity/impacket/issues/61, closing this one
