### ISSUE TITLE
Kerberos login not working for netapp and local samba server.

### ISSUE THREAD

**Issue by contactr2m** [CoreSecurity/impacket#247]
This may not be a defect, i may be missing something but to (make sure / get more information) i have created it.   I suspect its my setup issue , can you please provide right steps to be taken ? 
Thanks
Mani

Attempt to connect from mac to local samba server using finder-> go->connect server. 
```
Macintosh-83~/Downloads: kinit devuser1@DEV.CC.ARRIAD.COM
devuser1@DEV.CC.ARRIAD.COM's password:

Before login
{{{
Macintosh-83~/Downloads: klist
Credentials cache: API:87CF03CC-0D6F-4419-87BB-B7151C35535D
        Principal: devuser1@DEV.CC.ARRIAD.COM

  Issued                Expires               Principal
Jan 11 21:58:09 2017  Jan 12 07:58:07 2017  krbtgt/DEV.CC.ARRIAD.COM@DEV.CC.ARRIAD.COM
}}}

After login
{{{
Macintosh-83~/Downloads: klist
Credentials cache: API:87CF03CC-0D6F-4419-87BB-B7151C35535D
        Principal: devuser1@DEV.CC.ARRIAD.COM

  Issued                Expires               Principal
Jan 11 21:58:09 2017  Jan 12 07:58:07 2017  krbtgt/DEV.CC.ARRIAD.COM@DEV.CC.ARRIAD.COM
Jan 11 21:59:33 2017  Jan 12 07:58:07 2017  cifs/loan4-vs1-3-client.cc.arriad.com@DEV.CC.ARRIAD.COM
}}}
```

Attempt to connect from mac to local server using impacket.
```
{{{
c = SMBConnection(remoteName='loan4-vs1-3-client.cc.arriad.com', remoteHost='loan4-vs1-3-client.cc.arriad.com', preferredDialect=514)
c.kerberosLogin('devuser1', 'devuser1', 'DEV.CC.ARRIAD.COM')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/impacket/smbconnection.py", line 330, in kerberosLogin
    raise SessionError(e.get_error_code(), e.get_error_packet())
SessionError: SMB SessionError: STATUS_LOGON_FAILURE(The attempted logon is invalid. This is either due to a bad username or authentication information.)
}}}
```
```
Macintosh-83~/Downloads: kinit devuser1@DEV.CC.ARRIAD.COM
devuser1@DEV.CC.ARRIAD.COM's password:

Before login attempt
{{{
Macintosh-83~/Downloads: klist
Credentials cache: API:87CF03CC-0D6F-4419-87BB-B7151C35535D
        Principal: devuser1@DEV.CC.ARRIAD.COM

  Issued                Expires               Principal
Jan 11 22:00:09 2017  Jan 12 08:00:07 2017  krbtgt/DEV.CC.ARRIAD.COM@DEV.CC.ARRIAD.COM
}}}

After login attempt. FAILED
{{{
Macintosh-83~/Downloads: klist
Credentials cache: API:87CF03CC-0D6F-4419-87BB-B7151C35535D
        Principal: devuser1@DEV.CC.ARRIAD.COM

  Issued                Expires               Principal
Jan 11 22:00:09 2017  Jan 12 08:00:07 2017  krbtgt/DEV.CC.ARRIAD.COM@DEV.CC.ARRIAD.COM
}}}
```

Comparing pacps for both i found this different.
Impacket pcap excerpt
```
{{{
negTokenInit
                        mechTypes: 1 item
                            MechType: 1.2.840.48018.1.2.2 (MS KRB5 - Microsoft Kerberos 5)
                        mechToken: 6e8205623082055ea003020105a10302010ea20703050000...
                        krb5_blob: 6e8205623082055ea003020105a10302010ea20703050000...
                                    ap-options: 00000000
                                        0... .... = reserved: False
                                        .0.. .... = use-session-key: False
                                        ..0. .... = mutual-required: False
                                        sname
                                            name-type: kRB5-NT-SRV-INST (2)
                                            sname-string: 2 items
                                                SNameString: cifs
                                                SNameString: loan4-vs1-3-client.cc.arriad.com <-- i tried using netbios name as loan4-gns actual name of cifs server and this is full fqdn.
I have these both entries in spn.
C:\Users\Administrator>setspn -l loan4-gns
Registered ServicePrincipalNames for CN=loan4-gns,CN=Computers,DC=dev,DC=cc,DC=arriad,DC=com:
        HOST/loan4-vs1-3-client.cc.arriad.com
        cifs/loan4-gns
        cifs/loan4-vs1-3-client.cc.arriad.com
        HOST/loan4-gns.dev.cc.arriad.com
        HOST/LOAN4-GNS
}}}
```

Mac pcap excerpt
```
{{{
negTokenInit
                        mechTypes: 2 items
                            MechType: 1.2.840.113554.1.2.2 (KRB5 - Kerberos 5)
                            MechType: 1.2.752.43.14.3 (iso.2.752.43.14.3)
                        mechToken: 608205dd06092a864886f71201020201006e8205cc308205...
                        krb5_blob: 608205dd06092a864886f71201020201006e8205cc308205...
                            KRB5 OID: 1.2.840.113554.1.2.2 (KRB5 - Kerberos 5)
                            krb5_tok_id: KRB5_AP_REQ (0x0001)                        
                                    ap-options: 20000000 (mutual-required)
                                        0... .... = reserved: False
                                        .0.. .... = use-session-key: False
                                        ..1. .... = mutual-required: True
                                        sname
                                            name-type: kRB5-NT-SRV-HST (3)
                                            sname-string: 2 items
                                                SNameString: cifs
                                                SNameString: loan4-vs1-3-client.cc.arriad.com
}}}

```

**Comment by martinuy** [comment]
@contactr2m, can you please attach to this ticket both pcap captures?

**Comment by contactr2m** [comment]
Here you go,

[Mac_kerb_local_samba_server.pcapng.zip](https://github.com/CoreSecurity/impacket/files/702663/Mac_kerb_local_samba_server.pcapng.zip)
[impacket_kerb_local_samba_server.pcapng.zip](https://github.com/CoreSecurity/impacket/files/702664/impacket_kerb_local_samba_server.pcapng.zip)

Thanks

**Comment by martinuy** [comment]
@contactr2m, thanks for your fast response! Can you please use Impacket's smbclient so we can make sure that the issue is not related to a programmatic issue when using the SMBConnection nor to a use of a ccache? The command would be the following: ./smbclient.py -debug -k
DEV.CC.ARRIAD.COM/devuser1@loan4-vs1-3-client.cc.arriad.com

**Comment by contactr2m** [comment]
```
{{{
Macintosh-83~: klist
Credentials cache: API:87CF03CC-0D6F-4419-87BB-B7151C35535D
        Principal: devuser1@DEV.CC.ARRIAD.COM

  Issued                Expires               Principal
Jan 12 14:45:05 2017  Jan 13 00:45:02 2017  krbtgt/DEV.CC.ARRIAD.COM@DEV.CC.ARRIAD.COM
}}}
```

```
{{{
Macintosh-83~: smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@loan4-vs1-3-client.cc.arriad.com
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[-] SMB SessionError: STATUS_LOGON_FAILURE(The attempted logon is invalid. This is either due to a bad username or authentication information.)
}}}
```

With -no-pass option
```
{{{
Macintosh-83~: smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@loan4-vs1-3-client.cc.arriad.com  -no-pass
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[-] Kerberos SessionError: KDC_ERR_PREAUTH_FAILED(Pre-authentication information was invalid)
}}}
```

**Comment by martinuy** [comment]
@contactr2m , is the domain controller a Samba?

**Comment by contactr2m** [comment]
No its, Windows Server 2008 R2 Enterprise

**Comment by contactr2m** [comment]
Different behavior for NetApp smb server.  I have included pcaps for both local and netapp server below.
```
With -no-pass option
{{{
rmahamuni@Macintosh-83~: smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@grapnel.cc.arriad.com -no-pass
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[-] Kerberos SessionError: KDC_ERR_PREAUTH_FAILED(Pre-authentication information was invalid)
}}}

With -no-pass option
{{{
rmahamuni@Macintosh-83~: smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@grapnel.cc.arriad.com
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
Type help for list of commands

<---- somehow it looks like connected here but its not. pcap shows status_more_processing_required.

# shares
[-] SMB SessionError: STATUS_WAIT_1(The caller specified WaitAny for WaitType and one of the dispatcher objects in the Object array has been set to the signaled state.)

# exit
}}}
```

[smbclient_kerb_netapp.pcapng.zip](https://github.com/CoreSecurity/impacket/files/702745/smbclient_kerb_netapp.pcapng.zip)
[smbclient_kerb_local_samba_server.pcapng.zip](https://github.com/CoreSecurity/impacket/files/702744/smbclient_kerb_local_samba_server.pcapng.zip)

**Comment by asolino** [comment]
Thanks for the data @contactr2m.

We're analyzing the pcaps, in particular the differences between a successful connection and the unsuccessful one.

We're seeing the target SPN type is different from impacket (NT_SRV_INST) and Mac (NT_SRV_HST). Let's see if changing it does something. So:

Replace NT_SRV_INST for NT_SRV_HST in both in [smb3.py](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb3.py#L583) and [smb.py](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb.py#L3077). This should end up being something like this:
```
serverName = Principal('cifs/%s' % (self._Connection['ServerName']),type=constants.PrincipalNameType.NT_SRV_HST.value)
``` 
and run again:
```
/smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@loan4-vs1-3-client.cc.arriad.com
```

**Comment by contactr2m** [comment]
```
{{{
Macintosh-83~/impacket:[master !] smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@loan4-vs1-3-client.cc.arriad.com
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[-] SMB SessionError: STATUS_LOGON_FAILURE(The attempted logon is invalid. This is either due to a bad username or authentication information.)
}}}
```
From pcap it looks like it got tgt and tgs both this time. but login failed.

[smbclient_kerb_local_samba_NT_SRV_HST.pcapng.zip](https://github.com/CoreSecurity/impacket/files/702834/smbclient_kerb_local_samba_NT_SRV_HST.pcapng.zip)

```
{{{
Macintosh-83~/impacket:[master !] git diff impacket/smb3.py
diff --git a/impacket/smb3.py b/impacket/smb3.py
index dc3ab88..627161d 100644
--- a/impacket/smb3.py
+++ b/impacket/smb3.py
@@ -580,7 +580,7 @@ class SMB3:
         # Now that we have the TGT, we should ask for a TGS for cifs

         if TGS is None:
-            serverName = Principal('cifs/%s' % (self._Connection['ServerName']), type=constants.PrincipalNameType.NT_SRV_INST.value)
+            serverName = Principal('cifs/%s' % (self._Connection['ServerName']), type=constants.PrincipalNameType.NT_SRV_HST.value)
             tgs, cipher, oldSessionKey, sessionKey = getKerberosTGS(serverName, domain, kdcHost, tgt, cipher, sessionKey)
         else:
             tgs = TGS['KDC_REP']
}}}
```

**Comment by contactr2m** [comment]
NetApp server throws,
 KRB Error: KRB5KRB_AP_ERR_MODIFIED, Error: STATUS_MORE_PROCESSING_REQUIRED

Change
```
{{{
Macintosh-83~/impacket:[master !] git diff impacket/smb.py
diff --git a/impacket/smb.py b/impacket/smb.py
index 7d35a3f..acbb716 100644
--- a/impacket/smb.py
+++ b/impacket/smb.py
@@ -3077,7 +3077,7 @@ class SMB:
         # Now that we have the TGT, we should ask for a TGS for cifs

         if TGS is None:
-            serverName = Principal('cifs/%s' % self.__remote_name, type=constants.PrincipalNameType.NT_SRV_INST.value)
+            serverName = Principal('cifs/%s' % self.__remote_name, type=constants.PrincipalNameType.NT_SRV_HST.value)
             tgs, cipher, oldSessionKey, sessionKey = getKerberosTGS(serverName, domain, kdcHost, tgt, cipher, sessionKey)
         else:
             tgs = TGS['KDC_REP']
}}}
```
[smbclient_kerb_netapp_NT_SRV_HST.pcapng.zip](https://github.com/CoreSecurity/impacket/files/702863/smbclient_kerb_netapp_NT_SRV_HST.pcapng.zip)

**Comment by asolino** [comment]
Hey @contactr2m 

I see a small difference in the GSSAPI blob. Please modify [this lines](https://github.com/CoreSecurity/impacket/blob/master/impacket/spnego.py#L354)
for:
```
        # Do we have tokens to send?
        if self.fields.has_key('MechToken'):
            mechToken = pack('B', ASN1_MECH_TOKEN) + asn1encode(
                pack('B', ASN1_OCTET_STRING) + asn1encode( pack('B', ASN1_AID) + asn1encode( '\x06\x09\x2a\x86\x48\x86\xf7\x12\x01\x02\x02\x01\x00' +
                    self['MechToken'])))
```
Please note this will break non kerberos connections. I just want to test this is what netapp server is expecting, and we'll go from there.
In a nutshell, change the lines commented above, and also mantain the changes in smb3.py / smb.py.
Then run again:
```
/smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@loan4-vs1-3-client.cc.arriad.com
```
Specifying the users's password of course ;)

thanks!

**Comment by contactr2m** [comment]
```
{{{
Macintosh-83~/impacket:[master !] git diff impacket/spnego.py
diff --git a/impacket/spnego.py b/impacket/spnego.py
index f177d18..95d7f12 100644
--- a/impacket/spnego.py
+++ b/impacket/spnego.py
@@ -353,9 +353,13 @@ class SPNEGO_NegTokenInit(GSSAPI):
         mechToken = ''
         # Do we have tokens to send?
         if self.fields.has_key('MechToken'):
+            # mechToken = pack('B', ASN1_MECH_TOKEN) + asn1encode(
+            #     pack('B', ASN1_OCTET_STRING) + asn1encode(
+            #         self['MechToken']))
             mechToken = pack('B', ASN1_MECH_TOKEN) + asn1encode(
                 pack('B', ASN1_OCTET_STRING) + asn1encode(
-                    self['MechToken']))
+                    pack('B', ASN1_AID) + asn1encode('\x06\x09\x2a\x86\x48\x86\xf7\x12\x01\x02\x02\x01\x00' +
+                                                     self['MechToken'])))

         ans = pack('B',SPNEGO_NegTokenInit.SPNEGO_NEG_TOKEN_INIT)
         ans += asn1encode(
}}}
```

Wow this change works !
Can you please explain what were we missing ? 

NetApp SMB1 
```
{{{
Macintosh-83~/impacket:[master !] smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@grapnel.cc.arriad.com
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
Type help for list of commands
# use rohit2
# ls
-rw-rw-rw-       6148  Wed Jan 11 21:59:41 2017 .DS_Store
-rw-rw-rw-       4096  Wed Jan 11 21:25:01 2017 ._.DS_Store
-rw-rw-rw-      16390  Thu Jan 12 22:23:56 2017 test7
drw-rw-rw-          0  Wed Jan 11 13:33:36 2017 dd
# exit
}}}
```
NetApp SMB2
```
{{{
Macintosh-83~/impacket:[master !] smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@river-0.cc.arriad.com
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
Type help for list of commands
# use rohitsim_ntfs
# ls
-rw-rw-rw-          0  Thu Dec 29 16:30:40 2016 test
-rw-rw-rw-       6148  Thu Jan 12 16:23:54 2017 .DS_Store
drw-rw-rw-          0  Wed Jan 11 03:00:27 2017 hello2
# exit
}}}
```

Local samba server SMB2
```
{{{
Macintosh-83~/impacket:[master !] smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@loan4-vs1-3-client.cc.arriad.com
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
Type help for list of commands
# use rohit2
# ls
drw-rw-rw-          0  Wed Jan 11 21:24:56 2017 .
-rw-rw-rw-      16390  Thu Jan 12 14:42:26 2017 test7
drw-rw-rw-          0  Wed Jan 11 13:33:36 2017 dd
-rw-rw-rw-       6148  Wed Jan 11 21:59:37 2017 .DS_Store
-rw-rw-rw-       4096  Wed Jan 11 21:24:56 2017 ._.DS_Store
# exit
}}}
```

**Comment by asolino** [comment]
> Wow this change works !
Can you please explain what were we missing ?

Good to know!..

Looks like this is what was missing:

![krb5](https://cloud.githubusercontent.com/assets/11577828/21936444/ebda704a-d98f-11e6-9ec2-d2a922384a68.png)

I originally thought these were optional fields, since Windows doesn't care about them, but looks like they're not.
Please do a final test with the original `NT_SRV_INST` in the Principal instance. If it still works then it is just this missing fields. 

I need to think an elegant fix for this that will take me some days.

**Comment by contactr2m** [comment]
smb3.py and smb.py change reverted.
```
{{{
Macintosh-83~/impacket:[master !] git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   impacket/spnego.py

no changes added to commit (use "git add" and/or "git commit -a")
}}}
```

With NT_SRV_INST, its working too.
```
{{{
Macintosh-83~/impacket:[master !] smbclient.py -debug -k DEV.CC.ARRIAD.COM/devuser1@loan4-vs1-3-client.cc.arriad.com
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
[+] Trying to connect to KDC at DEV.CC.ARRIAD.COM
Type help for list of commands
# info
Version Major: 4
Version Minor: 9
Server Name: LOAN4-GNS
Server Comment: Samba 4.0 Test Server
Server UserPath: C:\
Simultaneous Users: 4294967295
# exit
}}}
```

**Comment by asolino** [comment]
Looks like we nailed it down @contactr2m :)

Thanks again for your help! We'll work on the fix

**Comment by contactr2m** [comment]
Thanks to you @asolino and @martinuy 👍 
So what changes do i need to keep so that both Kerberos and normal ntlm login works for now ?
"Please note this will break non kerberos connections."  <-- what do you mean here ?

**Comment by asolino** [comment]
Hey @contactr2m 

Please remove all previous manual changes and pull the latest sources. Kerberos and non Kerberos logins should now work. 

Please let me know and close this issue accordingly.

thanks!

**Comment by contactr2m** [comment]
@asolino Both kerberos and non kerberos logins are working now thank you 💯 

Cheers 👍
