### ISSUE TITLE
NTLMRelayX Error

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#278]
```
Exception happened during processing of request from ('192.168.1.100', 31533)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 54, in __init__
    self.target = self.client_address[0]
AttributeError: HTTPHandler instance has no attribute 'client_address'
----------------------------------------
```

**Comment by mubix** [comment]
Happens when no target is specified, when a `-t` is specified it works just fine

**Comment by asolino** [comment]
Hey @mubix, please recheck and close this issue if working.

**Comment by mubix** [comment]
Definitely fixed, sorry for not closing earlier
