### ISSUE TITLE
Modifying a WMI Object's Read-Write Property

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#341]
Hey mate,

Quick question for you, I'm trying to modify a WMI object's property, judging from ```wmipersist.py``` I should be able to do this with the following code (at least from what I understand):

```python
from impacket.dcerpc.v5.dcomrt import DCOMConnection
from impacket.dcerpc.v5.dcom import wmi
from impacket.dcerpc.v5.dtypes import NULL


def check_error(banner, resp):
    if resp.GetCallStatus(0) != 0:
        print '%s - ERROR (0x%x)' % (banner, resp.GetCallStatus(0))
    else:
        print '%s - OK' % banner


dcom = DCOMConnection('172.16.164.11', 'Administrator', 'P@ssw0rd', 'LAB', oxidResolver=False)

iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login, wmi.IID_IWbemLevel1Login)
iWbemLevel1Login = wmi.IWbemLevel1Login(iInterface)
iWbemServices = iWbemLevel1Login.NTLMLogin('//./root/cimv2', NULL, NULL)
iWbemLevel1Login.RemRelease()

activeScript, callResult = iWbemServices.GetObject('Win32_OSRecoveryConfiguration')
activeScript = activeScript.SpawnInstance()
activeScript.DebugFilePath = 'Testing'

check_error('Writing to DebugFilePath', iWbemServices.PutInstance(activeScript.marshalMe()))

dcom.disconnect()
```

However every time I run it i get the following output:
```
Writing to DebugFilePath - ERROR (0x-7ffbefcb)
```

I can supply a packet capture if need be, just wanted to make sure I'm not missing anything obvious.

Thanks!

**Comment by asolino** [comment]
Hey @byt3bl33d3r 

At first sight it looks ok.. but I get the same error as you. There's gotta be a different way to do this. Maybe all the fields must be set (or, get the default fields somehow and just change the ones you want). 
We need to understand what a similar implementation (through Powershell for example) does. I'll see what I can do.

**Comment by byt3bl33d3r** [comment]
@asolino ah! awesome I'll give that a go, didn't think about trying to construct the object with the default fields. Will let you know

**Comment by byt3bl33d3r** [comment]
@asolino yup! that did it! thanks man. 

Just for anyone who is trying to do the same thing here is the code I used
```python
from impacket.dcerpc.v5.dcomrt import DCOMConnection
from impacket.dcerpc.v5.dcom import wmi
from impacket.dcerpc.v5.dtypes import NULL


def check_error(banner, resp):
    if resp.GetCallStatus(0) != 0:
        print '%s - ERROR (0x%x)' % (banner, resp.GetCallStatus(0))
    else:
        print '%s - OK' % banner


dcom = DCOMConnection('172.16.164.12', 'g0d', 'P@ssw0rd', 'LAB', oxidResolver=False)

iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login, wmi.IID_IWbemLevel1Login)
iWbemLevel1Login = wmi.IWbemLevel1Login(iInterface)
iWbemServices = iWbemLevel1Login.NTLMLogin('//./root/cimv2', NULL, NULL)
iWbemLevel1Login.RemRelease()

activeScript, callResult = iWbemServices.GetObject('Win32_OSRecoveryConfiguration')
activeScript = activeScript.SpawnInstance()
activeScript.SettingID = 0
activeScript.Caption = 0
activeScript.Description = 0
activeScript.AutoReboot = True
activeScript.DebugFilePath = 'Samantha'
activeScript.ExpandedDebugFilePath = 'C:\WINDOWS\MEMORY.DMP'
activeScript.MiniDumpDirectory = '%SystemRoot%\Minidump'
activeScript.ExpandedMiniDumpDirectory = 'C:\WINDOWS\Minidump'
activeScript.Name = 'Microsoft Windows 10 Pro|C:\WINDOWS|\Device\Harddisk0\Partition2'
activeScript.OverwriteExistingDebugFile = True
activeScript.SendAdminAlert = 0
activeScript.WriteDebugInfo = True
activeScript.DebugInfoType = 7
activeScript.WriteToSystemLog = True
activeScript.KernelDumpOnly = 0

check_error('Writing to DebugFilePath', iWbemServices.PutInstance(activeScript.marshalMe()))

dcom.disconnect()
```

Cheers!

**Comment by koushui** [comment]
Hey everynone,

Now I also encounter the same problem, my script running environment is Windows 11 Simplified Chinese version, and the Ubuntu 20.04 (-standard-WSL2 x86_64) that comes with Windows, the target machine is Windows 10 Simplified Chinese version. There are three cases of errors.

Case 1, whether win or ubuntu runs the above byt3bl33d3r code, the windows error message is:
```
PropName 'SettingID', Value: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/impacket/structure.py", line 126, in getData
    data += self. packField(field[0], field[1])
  File "/usr/local/lib/python3.8/dist-packages/impacket/structure.py", line 111, in packField
    ans = self.pack(format, self.fields[fieldName], field = fieldName)
  File "/usr/local/lib/python3.8/dist-packages/impacket/structure.py", line 250, in pack
    return bytes(b(data)+b('\0'))
  File "/usr/lib/python3/dist-packages/six.py", line 628, in b
    return s.encode("latin-1")
AttributeError: 'int' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 38, in <module>
    check_error('Writing to DebugFilePath', iWbemServices.PutInstance(activeScript.marshalMe()))
  File "/usr/local/lib/python3.8/dist-packages/impacket/dcerpc/v5/dcom/wmi.py", line 2473, in marshalMe
    instanceHeap += strIn. getData()
  File "/usr/local/lib/python3.8/dist-packages/impacket/structure.py", line 129, in getData
    e.args += ("When packing field '%s | %s | %r' in %s" % (field[0], field[1], self[field[0]], self.__class__),)
  File "/usr/local/lib/python3.8/dist-packages/impacket/dcerpc/v5/dcom/wmi.py", line 164, in __getitem__
    if key == 'Character' and self.isUnicode:
AttributeError: 'ENCODED_STRING' object has no attribute 'isUnicode'
```

In case 2, I first try to use iWbemServices.ExecQuery('Select * From Win32_OSRecoveryConfiguration') to get all the fields of Win32_OSRecoveryConfiguration of the target machine, and then fill them into my own object fields, and finally execute iWbemServices.PutInstance(activeScript.marshalMe()) Submit, program returns returns ERROR (0x-7ffbefcb)


Case 3, based on case 2, I refer to "https://github.com/Orange-Cyberdefense/cme-wmi/blob/7513ac4408e47951a3410f665c08d9173d9e783b/wmi.py to cast the field type, such as:
```
wmiClass. SettingID = str(wmiClass. SettingID)
wmiClass. Caption = str(wmiClass. Caption)
wmiClass. Description = str(wmiClass. Description)
wmiClass.AutoReboot = int(wmiClass.AutoReboot == 'True')
wmiClass.OverwriteExistingDebugFile = int(wmiClass.OverwriteExistingDebugFile == 'True')
wmiClass.WriteDebugInfo = int(wmiClass.WriteDebugInfo == 'True')
wmiClass.WriteToSystemLog = int(wmiClass.WriteToSystemLog == 'True')
wmiClass.DebugFilePath = update_value
wmiClass. ExpandedDebugFilePath = ""
```

Finally execute iWbemServices.PutInstance(wmiClass.marshalMe()) to submit, and finally the program returns ERROR (0x-2147217355)

Finally, I feel that the program has problems with WMI Object's Write Property, which should be caused by encoding,Can anyone help me with this problem? thanks
