### ISSUE TITLE
impacket-0.9.18.dev0

### ISSUE THREAD

**Issue by fcafra** [CoreSecurity/impacket#472]
Hi, 
On Kali when i launch ntlmrelayx.py i have this error, 

Impacket v0.9.18-dev - Copyright 2002-2018 Core Security Technologies

[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
Traceback (most recent call last):
  File "/usr/local/bin/ntlmrelayx.py", line 4, in <module>
    __import__('pkg_resources').run_script('impacket==0.9.18.dev0', 'ntlmrelayx.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/impacket-0.9.18.dev0-py2.7.egg/EGG-INFO/scripts/ntlmrelayx.py", line 272, in <module>
    
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/attacks/__init__.py", line 50, in <module>
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/attacks/smbattack.py", line 24, in <module>
  File "build/bdist.linux-x86_64/egg/impacket/examples/smbclient.py", line 30, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/usr/lib/python2.7/ctypes/wintypes.py", line 19, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported

Can i ask an help please ?

**Comment by asolino** [comment]
Hey @fcafra 

Are you running Kali under Windows?

As can be seen from your output, you have a broken `pyreadline` installation. I don't know what the reason is for you to have that package installed under Kali, but it's definitely broken. You can either reinstall or remove it. 

Once that's done test all again. I'm closing this issue now. Feel free to reopen it if problem persists

**Comment by fcafra** [comment]
Oh sorry @asolino , I Succesfully uninstall pyreadline and now work. Many Thanks and sorry again.
